### ISSUE TITLE
порешать почему не работает `tfq `

### ISSUE THREAD

**Issue by vtrokhymenko** [quantum-ods/qmlcourse#392]
речь идет о лекции [Cirq & TFQ](https://quantum-ods.github.io/qmlcourse/book/prog/ru/cirq_tfq.html)

```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import tensorflow as tf
import tensorflow_quantum as tfq
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNotFoundError[0m                             Traceback (most recent call last)
[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/load_module.py[0m in [0;36mload_module[0;34m(name)[0m
[1;32m     41[0m         [0mpath[0m [0;34m=[0m [0mresource_loader[0m[0;34m.[0m[0mget_path_to_datafile[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 42[0;31m         [0;32mreturn[0m [0mload_library[0m[0;34m.[0m[0mload_op_library[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     43[0m     [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py[0m in [0;36mload_op_library[0;34m(library_filename)[0m
[1;32m     57[0m   """
[0;32m---> 58[0;31m   [0mlib_handle[0m [0;34m=[0m [0mpy_tf[0m[0;34m.[0m[0mTF_LoadLibrary[0m[0;34m([0m[0mlibrary_filename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m   [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mNotFoundError[0m: /usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl12lts_2021032411string_viewEOSt6vectorINS_10StackFrameESaIS7_EE

During handling of the above exception, another exception occurred:

[0;31mNotFoundError[0m                             Traceback (most recent call last)
[0;32m/tmp/ipykernel_7256/3324038471.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mos[0m[0;34m.[0m[0menviron[0m[0;34m[[0m[0;34m"TF_CPP_MIN_LOG_LEVEL"[0m[0;34m][0m [0;34m=[0m [0;34m"3"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mtensorflow[0m [0;32mas[0m [0mtf[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mimport[0m [0mtensorflow_quantum[0m [0;32mas[0m [0mtfq[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m [0;31m# Import basic ops and op getters.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m from tensorflow_quantum.core import (append_circuit, get_expectation_op,
[0m[1;32m     19[0m                                      [0mget_sampled_expectation_op[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m                                      [0mget_sampling_op[0m[0;34m,[0m [0mget_state_op[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m [0;34m"""Imports to tensorflow_quantum.core.* level."""[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0;31m# Import getters for constructing ops.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 17[0;31m from tensorflow_quantum.core.ops import (get_expectation_op,
[0m[1;32m     18[0m                                          [0mget_sampled_expectation_op[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m                                          [0mget_sampling_op[0m[0;34m,[0m [0mget_state_op[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m [0;31m# Import getters for constructing ops.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m from tensorflow_quantum.core.ops.circuit_execution_ops import (
[0m[1;32m     19[0m     [0mget_expectation_op[0m[0;34m,[0m [0mget_sampled_expectation_op[0m[0;34m,[0m [0mget_sampling_op[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m     get_state_op)

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0;32mimport[0m [0mcirq[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m [0;34m[0m[0m
[0;32m---> 20[0;31m from tensorflow_quantum.core.ops import (cirq_ops, tfq_simulate_ops,
[0m[1;32m     21[0m                                          tfq_utility_ops)
[1;32m     22[0m [0;32mfrom[0m [0mtensorflow_quantum[0m[0;34m.[0m[0mpython[0m [0;32mimport[0m [0mquantum_context[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py[0m in [0;36m<module>[0;34m[0m
[1;32m     17[0m [0;32mfrom[0m [0mtensorflow_quantum[0m[0;34m.[0m[0mcore[0m[0;34m.[0m[0mops[0m[0;34m.[0m[0mload_module[0m [0;32mimport[0m [0mload_module[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m
[0;32m---> 19[0;31m [0mSIM_OP_MODULE[0m [0;34m=[0m [0mload_module[0m[0;34m([0m[0;34m"_tfq_simulate_ops.so"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0;34m[0m[0m
[1;32m     21[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/load_module.py[0m in [0;36mload_module[0;34m(name)[0m
[1;32m     44[0m         path = os.path.join(get_python_lib(), "tensorflow_quantum/core/ops",
[1;32m     45[0m                             name)
[0;32m---> 46[0;31m         [0;32mreturn[0m [0mload_library[0m[0;34m.[0m[0mload_op_library[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py[0m in [0;36mload_op_library[0;34m(library_filename)[0m
[1;32m     56[0m     [0mRuntimeError[0m[0;34m:[0m [0mwhen[0m [0munable[0m [0mto[0m [0mload[0m [0mthe[0m [0mlibrary[0m [0;32mor[0m [0mget[0m [0mthe[0m [0mpython[0m [0mwrappers[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m     57[0m   """
[0;32m---> 58[0;31m   [0mlib_handle[0m [0;34m=[0m [0mpy_tf[0m[0;34m.[0m[0mTF_LoadLibrary[0m[0;34m([0m[0mlibrary_filename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     59[0m   [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     60[0m     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

[0;31mNotFoundError[0m: /usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl12lts_2021032411string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
NotFoundError: /usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl12lts_2021032411string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
```

**Comment by alexey-pronkin** [comment]
Я предлагаю поддерживать две версии деплоя, одну через poetry, другую через конду. Просто все продублируем.
Я мотивирую это тем, что иногда студентам нужно делать и проходить курсы с помощью определенного софта, поэтому psi4 выпиливать не хочется. В идеале вообще ничего не выпиливать, а хранить и стараться поддержать все фреймворки. Только делать это в парадигме микросервисов, т.е. пусть живут лекции своей жизнью, а в курс будем добавлять те, что собираются успешно на данный момент. Те, что не работают помечать как то

**Comment by vtrokhymenko** [comment]
> Я предлагаю поддерживать две версии деплоя, одну через poetry, другую через конду. Просто все продублируем.
Я мотивирую это тем, что иногда студентам нужно делать и проходить курсы с помощью определенного софта, поэтому psi4 выпиливать не хочется. В идеале вообще ничего не выпиливать, а хранить и стараться поддержать все фреймворки. Только делать это в парадигме микросервисов, т.е. пусть живут лекции своей жизнью, а в курс будем добавлять те, что собираются успешно на данный момент. Те, что не работают помечать как то

также думал об этом и не раз. но psi4 (хоть в этом issue о tfq) на ровном месте нам делает не одну доп задачу. как вариант, код psi4 можем оставить, но написать что пусть на colab его потыкают

поддерживать в нашем случае всё и вся безумно сложно и не факт что нужно с учетом нашего времени, которе не безгранично
